# Generated by Django 4.1.1 on 2023-02-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patent', '0002_patentapplication_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assignedto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20)),
                ('assignto', models.CharField(max_length=20)),
                ('assignstatus', models.BooleanField(default=False)),
            ],
        ),
    ]
