# Generated by Django 4.1.1 on 2023-03-19 17:01

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Patent', '0004_patentapplication_idf_patentapplication_nda_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='noveltystatus',
            name='assignto',
            field=models.CharField(default=' ', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noveltystatus',
            name='duedate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noveltystatus',
            name='qc',
            field=models.CharField(default=' ', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='noveltystatus',
            name='rating',
            field=models.CharField(default=' ', max_length=10),
            preserve_default=False,
        ),
    ]
