# Generated by Django 4.1.1 on 2023-04-14 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patent', '0005_noveltystatus_assignto_noveltystatus_duedate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='drawingstatus',
            name='assignto',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drawingstatus',
            name='duedate',
            field=models.DateField(default='2023-04-20', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drawingstatus',
            name='qc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drawingstatus',
            name='rating',
            field=models.CharField(default='0', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='noveltystatus',
            name='duedate',
            field=models.DateField(null=True),
        ),
    ]
