# Generated by Django 4.1.1 on 2023-06-02 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patent', '0007_alter_drawingstatus_duedate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignedto',
            name='assignto',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='drawingstatus',
            name='assignto',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ndastatus',
            name='nda',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='ndastatus',
            name='uid',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='noveltystatus',
            name='assignto',
            field=models.CharField(max_length=50),
        ),
    ]
