# Generated by Django 4.1.1 on 2023-06-11 18:13

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('Patent', '0008_alter_assignedto_assignto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftingstatus',
            name='assignto',
            field=models.CharField(default=django.utils.timezone.now, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='draftingstatus',
            name='duedate',
            field=models.DateField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='draftingstatus',
            name='qc',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='draftingstatus',
            name='rating',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='drawingstatus',
            name='drawings',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
    ]
