# Generated by Django 4.1.1 on 2023-06-11 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patent', '0009_draftingstatus_assignto_draftingstatus_duedate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftingstatus',
            name='drawings',
            field=models.CharField(default=' ', max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='draftingstatus',
            name='qc',
            field=models.CharField(max_length=10),
        ),
    ]
