# Generated by Django 4.1.1 on 2023-06-12 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patent', '0010_draftingstatus_drawings_alter_draftingstatus_qc'),
    ]

    operations = [
        migrations.AddField(
            model_name='draftingstatus',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drawingstatus',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='noveltystatus',
            name='approved',
            field=models.BooleanField(default=False),
        ),
    ]
