# Generated by Django 4.1.1 on 2023-06-19 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patent', '0011_draftingstatus_approved_drawingstatus_approved_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ferstatus',
            name='date',
        ),
        migrations.AddField(
            model_name='ferstatus',
            name='approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ferstatus',
            name='assignto',
            field=models.CharField(default=' ', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ferstatus',
            name='duedate',
            field=models.DateField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='ferstatus',
            name='qc',
            field=models.CharField(default=' ', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ferstatus',
            name='rating',
            field=models.CharField(default=' ', max_length=20),
            preserve_default=False,
        ),
    ]
