# Generated by Django 4.1.1 on 2023-06-19 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patent', '0013_alter_draftingstatus_qc_alter_drawingstatus_qc_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ferstatus',
            name='qc',
            field=models.CharField(max_length=20),
        ),
    ]
