# Generated by Django 4.1.1 on 2023-06-21 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patent', '0014_alter_ferstatus_qc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patentapplication',
            name='patenttype',
            field=models.CharField(max_length=100),
        ),
    ]
