# Generated by Django 4.1.1 on 2023-06-22 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patent', '0015_alter_patentapplication_patenttype'),
    ]

    operations = [
        migrations.CreateModel(
            name='IdeaDevelopmentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.BooleanField(default=False)),
                ('uid', models.CharField(max_length=20)),
                ('rating', models.CharField(max_length=20)),
                ('assignto', models.CharField(max_length=50)),
                ('duedate', models.DateField(max_length=20, null=True)),
                ('qc', models.CharField(max_length=20)),
                ('drawings', models.CharField(max_length=30)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
    ]
